# Generated by Django 2.1.5 on 2019-01-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('text', 'stop_word')},
        ),
    ]
