# Generated by Django 2.2.3 on 2019-08-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_quote_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StopWord',
            new_name='Tag',
        ),
    ]
