# Generated by Django 2.2.3 on 2019-08-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20190820_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='stop_word',
            new_name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('text', 'tag')},
        ),
    ]
