# Generated by Django 2.2.3 on 2020-02-07 19:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow_camera', '0002_auto_20200207_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=list, size=None),
        ),
    ]
