# Generated by Django 2.2.3 on 2020-02-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow_camera', '0003_location_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
